// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// simulate_cdfs_cpp
NumericVector simulate_cdfs_cpp(int iterations, int grid_points);
RcppExport SEXP _artma_simulate_cdfs_cpp(SEXP iterationsSEXP, SEXP grid_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type grid_points(grid_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_cdfs_cpp(iterations, grid_points));
    return rcpp_result_gen;
END_RCPP
}
// simulate_cdfs_block_cpp
NumericVector simulate_cdfs_block_cpp(const NumericMatrix& eps_block);
RcppExport SEXP _artma_simulate_cdfs_block_cpp(SEXP eps_blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type eps_block(eps_blockSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_cdfs_block_cpp(eps_block));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_artma_simulate_cdfs_cpp", (DL_FUNC) &_artma_simulate_cdfs_cpp, 2},
    {"_artma_simulate_cdfs_block_cpp", (DL_FUNC) &_artma_simulate_cdfs_block_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_artma(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
