# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_cdfs_cpp <- function(iterations, grid_points) {
    .Call(`_artma_simulate_cdfs_cpp`, iterations, grid_points)
}

simulate_cdfs_block_cpp <- function(eps_block) {
    .Call(`_artma_simulate_cdfs_block_cpp`, eps_block)
}

